name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup network
        run: docker network create test-network
      - name: Build the stack
        run: docker compose -f tests/docker-compose.yml build
      - name: Start the stack
        run: docker compose -f tests/docker-compose.yml up -d cert_auth gateway
      - name: Run test container
        run: docker compose -f tests/docker-compose.yml run test